
DROP DATABASE securecapita;
CREATE DATABASE securecapita;

USE securecapita;
CREATE TABLE Roles
(
    id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name            VARCHAR(50) NOT NULL,
    permissions     VARCHAR(255) NOT NULL,
    CONSTRAINT UQ_Roles_Name UNIQUE (name)
);

INSERT INTO Roles(name, permissions)
	VALUES('ROLE_USER','READ:USER,READ:CUSTOMER'),
		('ROLE_MANAGER','READ:USER,READ:CUSTOMER,UPDATE:USER,UPDATE:CUSTOMER'),
        ('ROLE_ADMIN','READ:USER,READ:CUSTOMER,UPDATE:USER,UPDATE:CUSTOMER,CREATE:USER,CREATE:CUSTOMER'),
        ('ROLE_SYSADMIN','READ:USER,READ:CUSTOMER,UPDATE:USER,UPDATE:CUSTOMER,CREATE:USER,CREATE:CUSTOMER,
        DELETE:USER,DELETE:CUSTOMER');