spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securecapita
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true

  sql:
    init:
      mode: always
      continue-on-error: false

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration





